export type IntentType = 'Transactionnelle' | 'Commerciale Haute' | 'Informationnelle';

export interface IntentDevis {
  id: string;
  question: string;
  primaryKeywords: string;
  volumeTrend: string;
  intent: IntentType;
  serviceVector: string;
  clientVector: string;
  geoZone: string;
  scoreIntention: number;
  scoreVolume: number;
  scoreCompetition: number;
  scoreBusinessValue: number;
  scoreGeo: number;
  /**
   * Priorité d'attaque normalisée sur 5 (moyenne des 5 critères).
   */
  priority: number;
}

/**
 * Base de données des intentions de devis identifiées pour MAB SECURITE.
 * Ces données servent de socle à la stratégie SEO et au plan de contenus.
 */
export const intentionsDevis: IntentDevis[] = [
  {
    id: 'SECU-001',
    question: 'Comment éviter les vols sur mon chantier la nuit ?',
    primaryKeywords:
      'gardiennage chantier nuit, sécurité chantier BTP, agent sécurité chantier',
    volumeTrend: 'Moyen-Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'BTP & Industrie',
    geoZone: 'Sud, Paris, Nord',
    scoreIntention: 5,
    scoreVolume: 4,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-002',
    question: "Quel est le coût d'un agent de sécurité pour un chantier ?",
    primaryKeywords:
      'tarif gardiennage chantier, prix agent sécurité chantier, devis sécurité BTP',
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'BTP & Industrie',
    geoZone: 'Toutes zones',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-003',
    question:
      "Comment sécuriser un chantier accessible avec plusieurs points d'entrée ?",
    primaryKeywords:
      'sécurisation chantier, gardiennage chantier ouvert, surveillance chantier multi-accès',
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'BTP & Industrie',
    geoZone: 'Toutes zones',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.0,
  },
  {
    id: 'SECU-004',
    question: 'Quelles sont mes obligations légales en sécurité sur un chantier ?',
    primaryKeywords:
      'obligation sécurité chantier, réglementation gardiennage BTP, conformité sécurité chantier',
    volumeTrend: 'Moyen-Élevé',
    intent: 'Informationnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'BTP & Industrie',
    geoZone: 'Toutes zones',
    scoreIntention: 3,
    scoreVolume: 4,
    scoreCompetition: 4,
    scoreBusinessValue: 3,
    scoreGeo: 4,
    priority: 3.6,
  },
  {
    id: 'SECU-005',
    question: 'Comment réduire les pertes liées aux vols en magasin ?',
    primaryKeywords:
      'agent sécurité magasin, gardiennage commerce, sécurité retail anti-vol',
    volumeTrend: 'Élevé',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Commerce & Retail',
    geoZone: 'Paris, Sud',
    scoreIntention: 4,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 5,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-006',
    question: 'Comment protéger mes employés face à des clients agressifs ?',
    primaryKeywords:
      'agent sécurité commerce, gestion conflit magasin, sécurité personnel retail',
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Commerce & Retail',
    geoZone: 'Paris, Sud',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.0,
  },
  {
    id: 'SECU-007',
    question:
      'Comment gérer les afflux massifs lors des soldes et Black Friday ?',
    primaryKeywords:
      'sécurité événementielle commerce, agent sécurité soldes, gestion foule magasin',
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Commerce & Retail',
    geoZone: 'Paris, Sud',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.0,
  },
  {
    id: 'SECU-008',
    question:
      "Comment sécuriser l'accès à nos bureaux tout en facilitant l'accueil ?",
    primaryKeywords:
      "contrôle accès bureaux, sécurité siège social, agent accueil sécurisé",
    volumeTrend: 'Élevé',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 4,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-009',
    question:
      'Comment prévenir les intrusions physiques visant à voler des informations ?',
    primaryKeywords:
      'sécurité siège social, protection données physique, surveillance zones sensibles',
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-010',
    question:
      "Quelles sont mes obligations SSIAP pour un immeuble de bureaux de plus de 28 mètres ?",
    primaryKeywords:
      'obligation SSIAP IGH, agent SSIAP immeuble bureaux, réglementation IGH Paris',
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.6,
  },
  {
    id: 'SECU-011',
    question:
      "Comment sécuriser un entrepôt logistique 24/7 avec des flux constants ?",
    primaryKeywords:
      'gardiennage entrepôt 24/7, sécurité plateforme logistique, surveillance entrepôt',
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Logistique',
    geoZone: 'Paris, Nord',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 5,
    scoreGeo: 4,
    priority: 4.4,
  },
  {
    id: 'SECU-012',
    question:
      "Comment garantir l'intégrité des marchandises de la réception à l'expédition ?",
    primaryKeywords:
      'sécurité chaîne approvisionnement, surveillance entrepôt logistique, contrôle accès quai',
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Logistique',
    geoZone: 'Paris, Nord',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 4,
    priority: 4.0,
  },
  {
    id: 'SECU-013',
    question:
      "Comment sécuriser un entrepôt stockant des produits chimiques ?",
    primaryKeywords:
      'sécurité entrepôt produits dangereux, gardiennage site ICPE, surveillance matières dangereuses',
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Logistique',
    geoZone: 'Nord',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 3,
    priority: 3.8,
  },
  {
    id: 'SECU-014',
    question:
      "Comment assurer la sécurité d'un événement accueillant plusieurs milliers de personnes ?",
    primaryKeywords:
      'sécurité événementielle, agent sécurité festival, gardiennage concert',
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Événementiel',
    geoZone: 'Sud, Paris',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-015',
    question:
      "Comment éviter les intrusions et la fraude aux billets lors d'un événement ?",
    primaryKeywords:
      "contrôle accès événement, agent sécurité billetterie, sécurité festival",
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Événementiel',
    geoZone: 'Sud, Paris',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.0,
  },
  {
    id: 'SECU-016',
    question:
      "Que faire en cas d'incident majeur lors d'un événement (incendie, alerte) ?",
    primaryKeywords:
      "plan évacuation événement, gestion crise festival, sécurité événementielle urgence",
    volumeTrend: 'Moyen',
    intent: 'Informationnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Événementiel',
    geoZone: 'Sud, Paris',
    scoreIntention: 3,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 3,
    scoreGeo: 5,
    priority: 3.6,
  },
  {
    id: 'SECU-017',
    question:
      'Quelle solution de vidéosurveillance autonome pour un chantier isolé ?',
    primaryKeywords:
      'vidéosurveillance chantier autonome, caméra chantier solaire, surveillance chantier 4G',
    volumeTrend: 'Moyen-Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Électronique',
    clientVector: 'BTP & Industrie',
    geoZone: 'Toutes zones',
    scoreIntention: 5,
    scoreVolume: 4,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-018',
    question: 'Comment installer de la vidéosurveillance en respectant le RGPD ?',
    primaryKeywords:
      'vidéosurveillance RGPD entreprise, conformité caméras bureaux, installation caméra CNIL',
    volumeTrend: 'Élevé',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Électronique',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 4,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-019',
    question:
      'Comment utiliser la vidéosurveillance pour réduire la démarque sans surveiller en permanence ?',
    primaryKeywords:
      'vidéosurveillance intelligente commerce, IA détection vol magasin, caméra anti-vol retail',
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Électronique',
    clientVector: 'Commerce & Retail',
    geoZone: 'Paris, Sud',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-020',
    question:
      'Comment moderniser le système de badges de mon immeuble de bureaux ?',
    primaryKeywords:
      "contrôle accès intelligent, badge RFID entreprise, système accès biométrique",
    volumeTrend: 'Moyen-Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Électronique',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 4,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-021',
    question:
      "Quelle solution d'alarme pour une boutique en centre-ville avec télésurveillance ?",
    primaryKeywords:
      'alarme intrusion boutique, télésurveillance commerce, système alarme magasin',
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Électronique',
    clientVector: 'Commerce & Retail',
    geoZone: 'Paris, Sud',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-022',
    question:
      'Comment surveiller en temps réel les opérations de chargement/déchargement 24/7 ?',
    primaryKeywords:
      'vidéosurveillance entrepôt, caméra quai chargement, surveillance logistique temps réel',
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Électronique',
    clientVector: 'Logistique',
    geoZone: 'Paris, Nord',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 4,
    priority: 3.8,
  },
  {
    id: 'SECU-023',
    question:
      'Quelle solution de détection incendie pour un entrepôt de 10,000 m² ?',
    primaryKeywords:
      "détection incendie entrepôt, alarme incendie logistique, système SSI entrepôt",
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'Logistique',
    geoZone: 'Paris, Nord',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 4,
    priority: 4.0,
  },
  {
    id: 'SECU-024',
    question:
      "Quelles sont mes obligations en sécurité incendie sur un chantier ?",
    primaryKeywords:
      'sécurité incendie chantier, obligation extincteur BTP, conformité incendie chantier',
    volumeTrend: 'Moyen-Élevé',
    intent: 'Informationnelle',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'BTP & Industrie',
    geoZone: 'Toutes zones',
    scoreIntention: 3,
    scoreVolume: 4,
    scoreCompetition: 4,
    scoreBusinessValue: 3,
    scoreGeo: 5,
    priority: 3.8,
  },
  {
    id: 'SECU-025',
    question:
      "Comment réaliser un audit de sécurité incendie pour une usine classée ICPE ?",
    primaryKeywords:
      'audit SSI usine, audit incendie site ICPE, vérification SSI industrie',
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'BTP & Industrie',
    geoZone: 'Nord',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 3,
    priority: 3.8,
  },
  {
    id: 'SECU-026',
    question:
      "Mon magasin est-il soumis aux obligations ERP et quelles sont-elles ?",
    primaryKeywords:
      'obligation ERP commerce, réglementation ERP magasin, classification ERP boutique',
    volumeTrend: 'Élevé',
    intent: 'Informationnelle',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'Commerce & Retail',
    geoZone: 'Toutes zones',
    scoreIntention: 3,
    scoreVolume: 5,
    scoreCompetition: 4,
    scoreBusinessValue: 3,
    scoreGeo: 5,
    priority: 4.0,
  },
  {
    id: 'SECU-027',
    question:
      "Comment former mes employés à réagir en cas d'incendie dans un centre commercial ?",
    primaryKeywords:
      'formation incendie commerce, manipulation extincteur employés, évacuation magasin',
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'Commerce & Retail',
    geoZone: 'Toutes zones',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 3,
    scoreGeo: 5,
    priority: 4.0,
  },
  {
    id: 'SECU-028',
    question:
      "Combien d'agents SSIAP dois-je avoir en permanence dans mon immeuble de 50 mètres ?",
    primaryKeywords:
      "obligation SSIAP IGH, nombre agents SSIAP, réglementation SSIAP immeuble",
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.6,
  },
  {
    id: 'SECU-029',
    question:
      'Comment vérifier que mon système de sécurité incendie est conforme ?',
    primaryKeywords:
      'audit SSI bureaux, vérification système incendie, conformité SSI entreprise',
    volumeTrend: 'Moyen-Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 4,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-030',
    question:
      "Quelle fréquence pour les exercices d'évacuation dans un immeuble de bureaux ?",
    primaryKeywords:
      "exercice évacuation bureaux, fréquence exercice incendie, obligation exercice IGH",
    volumeTrend: 'Moyen',
    intent: 'Informationnelle',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 3,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 3,
    scoreGeo: 5,
    priority: 3.6,
  },
  {
    id: 'SECU-031',
    question:
      "Quelles sont mes obligations en sécurité incendie pour un salon professionnel ?",
    primaryKeywords:
      'sécurité incendie événement, obligation SSIAP salon, moyens secours événement',
    volumeTrend: 'Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Sécurité Incendie',
    clientVector: 'Événementiel',
    geoZone: 'Sud, Paris',
    scoreIntention: 4,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 3,
    scoreGeo: 5,
    priority: 3.8,
  },
  {
    id: 'SECU-032',
    question:
      "Comment évaluer les risques de sécurité d'un chantier en zone sensible ?",
    primaryKeywords:
      'audit sûreté chantier, analyse risques chantier, évaluation sécurité BTP',
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'BTP & Industrie',
    geoZone: 'Toutes zones',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-033',
    question: 'Comment préparer mon usine à gérer une crise majeure ?',
    primaryKeywords:
      'plan gestion crise industrielle, procédures urgence usine, gestion crise site industriel',
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'BTP & Industrie',
    geoZone: 'Nord',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 3,
    priority: 4.0,
  },
  {
    id: 'SECU-034',
    question:
      "Comment obtenir la certification ISO 45001 pour mon site industriel ?",
    primaryKeywords:
      'certification ISO 45001, audit conformité sécurité, accompagnement ISO 45001',
    volumeTrend: 'Faible-Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'BTP & Industrie',
    geoZone: 'Nord',
    scoreIntention: 5,
    scoreVolume: 2,
    scoreCompetition: 5,
    scoreBusinessValue: 5,
    scoreGeo: 3,
    priority: 4.0,
  },
  {
    id: 'SECU-035',
    question:
      "Comment évaluer les risques de sécurité d'un centre commercial ?",
    primaryKeywords:
      'audit sûreté centre commercial, analyse risques retail, évaluation sécurité commerce',
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Commerce & Retail',
    geoZone: 'Paris, Sud',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-036',
    question:
      'Comment gérer une crise médiatique suite à un incident de sécurité ?',
    primaryKeywords:
      'gestion crise communication, cellule crise entreprise, communication incident sécurité',
    volumeTrend: 'Faible',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Commerce & Retail',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 2,
    scoreCompetition: 5,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-037',
    question:
      "Comment évaluer le niveau de sécurité de mon siège social ?",
    primaryKeywords:
      'audit sûreté siège social, évaluation sécurité entreprise, audit sécurité bureaux',
    volumeTrend: 'Moyen-Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 4,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 5,
    priority: 4.6,
  },
  {
    id: 'SECU-038',
    question:
      'Comment garantir la continuité de mes opérations en cas d\'incident majeur ?',
    primaryKeywords:
      'plan continuité activité, PCA entreprise, continuité opérationnelle',
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-039',
    question:
      "Comment protéger mes secrets industriels contre l'espionnage ?",
    primaryKeywords:
      'protection patrimoine immatériel, intelligence économique, sécurité secrets industriels',
    volumeTrend: 'Faible-Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 4,
    scoreVolume: 2,
    scoreCompetition: 5,
    scoreBusinessValue: 5,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-040',
    question:
      'Comment sécuriser ma supply chain de bout en bout ?',
    primaryKeywords:
      'sécurité chaîne approvisionnement, audit supply chain, sécurisation logistique',
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Logistique',
    geoZone: 'Paris, Nord',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 4,
    priority: 4.2,
  },
  {
    id: 'SECU-041',
    question:
      'Comment sécuriser le transport de produits high-tech ou pharmaceutiques ?',
    primaryKeywords:
      'transport sécurisé marchandises valeur, escorte transport, sécurité transport sensible',
    volumeTrend: 'Faible-Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Logistique',
    geoZone: 'Paris, Nord',
    scoreIntention: 5,
    scoreVolume: 2,
    scoreCompetition: 4,
    scoreBusinessValue: 5,
    scoreGeo: 4,
    priority: 4.0,
  },
  {
    id: 'SECU-042',
    question:
      "Comment élaborer un plan de sécurité pour un événement de grande envergure ?",
    primaryKeywords:
      'plan sécurité événement, analyse risques festival, dimensionnement sécurité événement',
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Événementiel',
    geoZone: 'Sud, Paris',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-043',
    question:
      "Comment organiser un PC sécurité efficace pour un festival ?",
    primaryKeywords:
      'PC sécurité événement, cellule commandement festival, coordination sécurité événement',
    volumeTrend: 'Faible-Moyen',
    intent: 'Commerciale Haute',
    serviceVector: 'Expertise & Conseil',
    clientVector: 'Événementiel',
    geoZone: 'Sud, Paris',
    scoreIntention: 4,
    scoreVolume: 2,
    scoreCompetition: 5,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.0,
  },
  {
    id: 'SECU-044',
    question: 'Agent de sécurité Nice - Tarifs et prestations',
    primaryKeywords:
      'agent sécurité Nice, gardiennage Nice, entreprise sécurité Nice',
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Multi-secteurs',
    geoZone: 'Sud',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-045',
    question: 'Agent de sécurité Marseille - Devis gratuit',
    primaryKeywords:
      'agent sécurité Marseille, gardiennage Marseille, société sécurité Marseille',
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Multi-secteurs',
    geoZone: 'Sud',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-046',
    question: 'Agent de sécurité Montpellier - Intervention rapide',
    primaryKeywords:
      'agent sécurité Montpellier, gardiennage Montpellier, entreprise sécurité Montpellier',
    volumeTrend: 'Moyen-Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Multi-secteurs',
    geoZone: 'Sud',
    scoreIntention: 5,
    scoreVolume: 4,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-047',
    question: 'Entreprise de sécurité Paris - Solutions complètes',
    primaryKeywords:
      'entreprise sécurité Paris, société gardiennage Paris, agence sécurité Paris',
    volumeTrend: 'Très Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Multi-services',
    clientVector: 'Multi-secteurs',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 2,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-048',
    question: 'Gardiennage Ile-de-France - Tous départements',
    primaryKeywords:
      'gardiennage IDF, sécurité Ile-de-France, agent sécurité 92 93 94',
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Multi-secteurs',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.4,
  },
  {
    id: 'SECU-049',
    question: 'Sécurité événementielle Cannes - Festivals et salons',
    primaryKeywords:
      'sécurité événementielle Cannes, agent sécurité festival Cannes, gardiennage salon Cannes',
    volumeTrend: 'Moyen',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Humaine',
    clientVector: 'Événementiel',
    geoZone: 'Sud',
    scoreIntention: 5,
    scoreVolume: 3,
    scoreCompetition: 4,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.2,
  },
  {
    id: 'SECU-050',
    question:
      'Vidéosurveillance entreprise Paris - Installation et maintenance',
    primaryKeywords:
      'vidéosurveillance entreprise Paris, installation caméra bureaux, système surveillance Paris',
    volumeTrend: 'Élevé',
    intent: 'Transactionnelle',
    serviceVector: 'Sécurité Électronique',
    clientVector: 'Tertiaire & Corporate',
    geoZone: 'Paris',
    scoreIntention: 5,
    scoreVolume: 5,
    scoreCompetition: 3,
    scoreBusinessValue: 4,
    scoreGeo: 5,
    priority: 4.4,
  },
];